easy_admin:
  site_name: 'Quiz Back-Office .'

  disabled_actions: ['new']

  list:
    actions:
      - { name: 'edit', icon: 'pencil' , label: false }
      - { name: 'delete', icon: 'trash', label: false }
      - { name: 'search', label: 'Rechercher' }
      - { name: 'show' , icon: 'eye' , label: false }


  entities:
    Participant:
      class: App\Entity\Participant

      list:
      action:
        fields:
          - { property: 'email', type: 'text' }
      show:
        fields:
          - { property: 'email', type: 'text' }




    ParticipantQuiz:
      class: App\Entity\ParticipantQuiz

      disabled_actions: ['edit','delete']

      label: 'Participants'
      list:
        fields:
          - { property: 'participant' , type: 'email' , label: 'Email participant'}
          - { property: 'quiz', type: 'text' , label: 'Quiz '}

      show:
        fields:
          - { property: 'participant', label: 'Email participant', type: 'email' }
          - { property: 'quiz', label: 'Quiz '}


      form:
        fields:
          - { property: 'participant', type: 'email' , label: 'Email participant'}
          - { property: 'quiz', type: 'text' , label: 'Quiz '}


    Quiz:
      class: App\Entity\Quiz
      controller: App\Controller\QuizController

      list:
        title: "Configuration"
        fields:
          - { property: 'titre', label: 'Titre de quiz'}
          - { property: 'terminer', label: 'Terminer' }
          - { property: 'ouvrire_quiz', label: 'Ouverture de quiz' }
          - { property: 'fermer_quiz', label: 'Fermeture de quiz'}
          - { property: 'timequiz'  , label: 'Temps' }
          - { property: 'nb_tentative', label: 'Nombre de tentative' }
          - { property: 'brochure', label: 'Logo' }
          - { property: 'melange_question', label: 'Mélanger les questions' }
          - { property: 'mode_correction', label: 'Mode correction et score' }



      action:
        fields:
          - { property: 'titre', type: 'text' , label: 'Titre de quiz'}
          - { property: 'description', type: 'text'  }
          - { property: 'mode_correction', type: 'boolean' }
          - { property: 'temps_dispo', type: 'datetime' }
          - { property: 'melange_question', type: 'boolean' }
          - { property: 'ouvrire_quiz', type: 'datetime' }
          - { property: 'fermer_quiz', type: 'datetime' }
          - { property: 'entete', type: 'text' }
          - { property: 'pied', type: 'text' }
          - { property: 'message_s', type: 'text' }
          - { property: 'message_e', type: 'text' }
          - { property: 'nb_tentative', type: 'integer' }
          - { property: 'terminer', type: 'boolean' }
          - { property: 'brochure', type: 'file' }
          - { property: 'timequiz' ,type: 'integer' }
          - { property: 'gras' ,type: 'boolean' }
          - { property: 'italique' ,type: 'boolean' }
          - { property: 'colorTitre' ,type: 'color'  }
          - { property: 'nb_page' , type: 'integer' }
          - { property: 'nb_question' , type: 'integer' }

      show:
        fields:
          - { property: 'titre', label: 'Titre de quiz'  }
          - { property: 'description', label: 'Description de quiz' }
          - { property: 'entete' , label: 'Entete de quiz' }
          - { property: 'pied' , label: 'Pied de quiz'}
          - { property: 'message_s', label: 'Message de succes' }
          - { property: 'message_e' , label: 'Message d''echec'}
          - { property: 'temps_dispo' }
          - { property: 'timequiz' ,label: 'Temps ' }
          - { property: 'melange_question' }
          - { property: 'ouvrire_quiz' }
          - { property: 'fermer_quiz' }
          - { property: 'mode_correction' }
          - { property: 'nb_tentative' ,label: 'Nombre de tentative disiponible' }
          - { property: 'nb_page' ,label: 'Nombre des pages' }
          - { property: 'nb_question' ,label: 'Nombre des questions par pages' }
          - { property: 'terminer' }
          - { property: 'brochure' ,label: 'Logo' , type: 'file' }
          - { property: 'gras' ,label: 'Titre en gras' }
          - { property: 'italique' ,label: 'Titre en italique' }
          - { property: 'colorTitre' ,label: 'Couleur de titre' }
      form:
        fields:
          - { type: 'tab', label: 'Info quiz' ,icon: 'wpforms' }
          - { property: 'titre', label: 'Titre de quiz'  }
          - { property: 'gras' ,label: 'Titre en gras' }
          - { property: 'italique' ,label: 'Titre en italique' }
          - { property: 'colorTitre' ,label: 'Couleur de titre', type: 'color' }
          - { property: 'description', label: 'Description de quiz' }
          - { property: 'entete' , label: 'Entete de quiz' }
          - { property: 'pied' , label: 'Pied de quiz'}
          - { property: 'message_s', label: 'Message de succes' }
          - { property: 'message_e' , label: 'Message d''echec'}
          - { type: 'tab', label: 'Parametrage', icon: 'cogs' }
          - { property: 'temps_dispo' }
          - { property: 'timequiz' ,label: 'Temps ' }
          - { property: 'melange_question' }
          - { property: 'ouvrire_quiz' }
          - { property: 'fermer_quiz' }
          - { property: 'mode_correction' }
          - { property: 'nb_tentative' ,label: 'Nombre de tentative disiponible' }
          - { property: 'nb_page' ,label: 'Nombre des pages' }
          - { property: 'nb_question' ,label: 'Nombre des questions par pages' }
          - { property: 'terminer' }
          - { type: 'tab', label: 'Logo', icon: 'download' }
          - { property: 'brochure' ,label: 'Logo' }



  design:
    menu:
      - { label: 'Dashboard', route: 'admin_dashboard', icon: 'tachometer' }
      - label: 'Quiz'
        icon: 'file'
        children:
          - { label: 'Créer Quiz', route: 'quiz_new', icon: 'wpforms' }
          - { label: 'Lister Quiz', route: 'list_quiz', icon: 'list-ol' }
      - { entity: 'Quiz', label: 'Configuration', icon: 'cogs' }
      - label: 'Utilisateurs'
        icon: 'users'
        children:
          - { entity: 'ParticipantQuiz', icon: 'user', label: 'Participants'  }
      - { label: 'Statiqtique',route: 'statistique', icon: 'fa fa-pie-chart' }
      - { label: 'Historiques',route: 'historique', icon: 'history' ,css_class: 'text-bold' }
    assets:
      css:
        - 'css/admin.css'
