easy_admin:
  site_name: 'Quiz Back-Office .'


  list:
    batch_actions: ['delete']
    actions:
      - { name: 'edit', icon: 'pencil' , label: false }
      - { name: 'delete', icon: 'trash', label: false }
      - { name: 'search', label: 'Rechercher' }
      - { name: 'show' , icon: 'eye' , label: false }


  entities:
    Participant:
      class: App\Entity\Participant

      list:
      action:
        fields:
          - { property: 'email', type: 'text' }
      show:
        fields:
          - { property: 'email', type: 'text' }




    ParticipantQuiz:
      class: App\Entity\ParticipantQuiz
      label: 'Participant'
      list:
      show:
        fields:
          - { property: 'User', type: 'integer' }
    Quiz:
      class: App\Entity\Quiz
      controller: App\Controller\QuizController

      label: 'Lister Quiz'
      list:
      action:
        fields:
          - { property: 'titre', type: 'text' }
          - { property: 'brochure', type: 'image', base_path: 'brochures_directory' }
          - { property: 'description', type: 'text' }
          - { property: 'mode_correction', type: 'boolean' }
          - { property: 'mode_score', type: 'boolean' }
          - { property: 'temps_dispo', type: 'datetime' }
          - { property: 'melange_question', type: 'boolean' }
          - { property: 'ouvrire_quiz', type: 'datetime' }
          - { property: 'fermer_quiz', type: 'datetime' }
          - { property: 'entete', type: 'text' }
          - { property: 'pied', type: 'text' }
          - { property: 'message_s', type: 'text' }
          - { property: 'message_e', type: 'text' }
          - { property: 'nb_tentative', type: 'integer' }
          - { property: 'terminer', type: 'boolean' }

        show:
          fields:
            - { type: 'group', columns: 4, label: 'Basic information' }
            - { property: 'description', type: 'text' }
            - { property: 'mode_correction', type: 'boolean' }
            - { property: 'brochure', type: 'image', base_path: 'brochures_directory' }

    User:
      class: App\Entity\User
      label: 'Admines'
      list:

          title: "Liste utilisateurs"
          fields:
            - { property: 'username', label: 'Nom utilisateur' }
            - { property: 'email', label: 'Email' }
            - { property: 'numerotel', label: 'Telephone' }
            - enabled
            - { property: 'lastLogin', label: 'Dernier login' }
            - { property: 'confirmation_token', label: 'Confermation code' , type: 'text', type_options: { required: false } }

      form:
        fields:
          - { type: 'group', columns: 4, label: 'Basic information' }

            # if administrators are allowed to edit users' passwords and roles, add this:
          - { property: 'username', label: 'Nom utilisateur' }
          - { property: 'email', label: 'Email' }
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'numerotel', type: 'tel' , label: 'Telephone'}

          - { type: 'group', label: 'securite information', icon: 'phone', columns: 6 }
          - enabled
          - lastLogin
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

  design:
    menu:
      - { label: 'Dashboard', route: 'admin_dashboard', icon: 'tachometer', default: true }
      - label: 'Quiz'
        icon: 'file'
        children:
          - { label: 'Créer Quiz', route: 'quiz_new', icon: 'wpforms' }
          - { label: 'Lister Quizzz', route: 'list_quiz', icon: 'list-ol' }
      - { entity: 'Quiz', label: 'Configuration', icon: 'cogs', }
      - label: 'Utilisateurs'
        icon: 'users'
        children:
          - { entity: 'User' , icon: 'user-plus' }
          - { entity: 'Participant', icon: 'user', label: 'Participants'  }
      - { label: 'Statiqtique',route: 'statistique', icon: 'fa fa-pie-chart' }
      - { label: 'Historiques',route: 'historique', icon: 'history' }
    assets:
      css:
        - 'css/admin.css'
