#index:
#    path: /
#    controller: App\Controller\DefaultController::index




question_dep:
    path: /question/{question}/duplication
    controller: App\Controller\QuestionController::questionDepAction
    requirements:
        methods: GET


actif:
    path: /question/{question}/activ
    controller: App\Controller\QuestionController::questionActifAction
    requirements:
        methods: GET

easy_admin_bundle:
    controller: App\Controller\AdminController::adlin
    path:   /admin